name    'treydock-atd'
version '0.0.1'
source 'git://github.com/treydock/puppet-atd.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Puppet module to manage atd'
description 'Puppet module to manage atd'
project_page 'https://github.com/treydock/puppet-atd'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
